# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/warsaw/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/warsaw/proprietary/vendor/etc/libnfc-brcm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-brcm.conf \
    vendor/huawei/warsaw/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/huawei/warsaw/proprietary/vendor/etc/cfg_warsaw_al00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_warsaw_al00_hisi.ini \
    vendor/huawei/warsaw/proprietary/vendor/etc/cfg_warsaw_l03t_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_warsaw_l03t_hisi.ini \
    vendor/huawei/warsaw/proprietary/vendor/etc/cfg_warsaw_lx1_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_warsaw_lx1_hisi.ini \
    vendor/huawei/warsaw/proprietary/vendor/etc/cfg_warsaw_lx1a_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_warsaw_lx1a_hisi.ini \
    vendor/huawei/warsaw/proprietary/vendor/etc/cfg_warsaw_lx2_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_warsaw_lx2_hisi.ini \
    vendor/huawei/warsaw/proprietary/vendor/etc/cfg_warsaw_lx2j_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_warsaw_lx2j_hisi.ini \
    vendor/huawei/warsaw/proprietary/vendor/etc/cfg_warsaw_lx3_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_warsaw_lx3_hisi.ini \
    vendor/huawei/warsaw/proprietary/vendor/etc/cfg_warsaw_tl00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_warsaw_tl00_hisi.ini
